// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testetobr.Data;

namespace testetobr.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210128010510_CreateModels")]
    partial class CreateModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("TradebookApi.Models.Moeda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Moeda");
                });

            modelBuilder.Entity("TradebookApi.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Nota");
                });

            modelBuilder.Entity("TradebookApi.Models.Operacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Operacao");
                });

            modelBuilder.Entity("TradebookApi.Models.SaidaTroco", b =>
                {
                    b.Property<int>("IdSaidaTroco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdMoeda")
                        .HasColumnType("int");

                    b.Property<int>("IdNota")
                        .HasColumnType("int");

                    b.Property<int>("IdOperacao")
                        .HasColumnType("int");

                    b.Property<int?>("MoedaId")
                        .HasColumnType("int");

                    b.Property<int?>("NotaId")
                        .HasColumnType("int");

                    b.Property<int?>("OperacaoId")
                        .HasColumnType("int");

                    b.HasKey("IdSaidaTroco");

                    b.HasIndex("MoedaId");

                    b.HasIndex("NotaId");

                    b.HasIndex("OperacaoId");

                    b.ToTable("SaidaTroco");
                });

            modelBuilder.Entity("TradebookApi.Models.SaidaTroco", b =>
                {
                    b.HasOne("TradebookApi.Models.Moeda", "Moeda")
                        .WithMany()
                        .HasForeignKey("MoedaId");

                    b.HasOne("TradebookApi.Models.Nota", "Nota")
                        .WithMany()
                        .HasForeignKey("NotaId");

                    b.HasOne("TradebookApi.Models.Operacao", "Operacao")
                        .WithMany()
                        .HasForeignKey("OperacaoId");

                    b.Navigation("Moeda");

                    b.Navigation("Nota");

                    b.Navigation("Operacao");
                });
#pragma warning restore 612, 618
        }
    }
}
